#!/bin/bash
cd /usr/share/nginx/html
sudo rm -r assets atom.xml blog font FontAwesome.ttf img index.html projects resume resume.pdf rss.xml
cd ~/code/lucid3.org/_site
sudo cp -r * /usr/share/nginx/html
cd /usr/share/nginx/html
sudo chown www-data:www-data -R .
